/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Foundational Concepts',
      items: [{type: 'autogenerated', dirName: 'foundational-concepts'}],
    },
    {
      type: 'category',
      label: 'Common Myths',
      items: [{type: 'autogenerated', dirName: 'common-myths'}],
    },
    {
      type: 'category',
      label: 'Research & Sources',
      items: [{type: 'autogenerated', dirName: 'research-and-sources'}],
    },
    {
      type: 'category',
      label: 'Community Stories',
      items: [{type: 'autogenerated', dirName: 'community-stories'}],
    },
  ],
};

export default sidebars;
